dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  sol:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
  solc:
    version: 0.6.6
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  kovan:
    usd_eth_pricefeed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    usd_eth_pricefeed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-home:
    verify: False